name: rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: rust build
    runs-on: self-hosted
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib && sudo apt-get install -y build-essential clang gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libclang-dev pkg-config libssl-dev
    - name: install rust
      run: |
       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
       source "$HOME/.cargo/env"
       cargo --version
       git clone https://github.com/nervosnetwork/ckb.git
       cd ckb
       make prod
       ./target/prod/ckb --version
        
